### ISSUE TITLE
Can't change transmission power without debug?

### ISSUE THREAD

**Issue by thekurtovic** [h2zero/esp-nimble-cpp#124] opened 2023-05-31 18:19 UTC
I wanted to make sure my esp32-s3 was using the highest value for transmission power, but for some reason it doesn't seem to change unless I have sdkconfig.h setup with these.
CONFIG_NIMBLE_CPP_LOG_LEVEL_DEBUG=y
CONFIG_NIMBLE_CPP_LOG_LEVEL=4

Testing with code like this
btStarted();
NimBLEDevice::init("test");
int before = NimBLEDevice::getPower();
Serial.printf("ble power before %i\n", before);
NimBLEDevice::setPower(ESP_PWR_LVL_P9);
int after  = NimBLEDevice::getPower();
Serial.printf("ble power after %i\n", after);

Output without debug
ble power before 3
ble power after 3

Output with debug
ble power before 3
D (3534) NimBLEDevice: >> setPower: 11 (type: 11)
D (3534) NimBLEDevice: << setPower
ble power after 9

**Comment by h2zero** [comment] 2023-06-24 02:25
This may be an issue with espressif, this library simply calls the espressif function to set the power level.

**Comment by h2zero** [comment] 2024-06-14 18:36
Closing this as unable to reproduce, working as expected now.

**Closed by h2zero** 2024-06-14 18:36 UTC
